import type { Puzzle } from "./types.ts";
import { Day7 } from "./day7.ts";

describe("day7", () => {
  let puzzle: Puzzle;

  beforeEach(() => {
    puzzle = new Day7(
      `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`,
    );
  });

  it("part one should return 21", async () => {
    const solution = await puzzle.part1();
    expect(solution).toBe(21);
  });

  it("part two should return 40", async () => {
    const solution = await puzzle.part2();
    expect(solution).toBe(40);
  });
});
